apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clone-datalake-harry
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nas-silver
  dataSource:
    name: snap-datalake
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
