kind: Pod
apiVersion: v1
metadata:
  name: pvpod-nas1
spec:
  volumes:
    - name: task-pv-storage
      persistentVolumeClaim:
       claimName: persistent-volume-claim-nas
  containers:
    - name: task-pv-container
      image: alpine:3.2
      command:
        - /bin/sh
        - "-c"
        - "sleep 60m"
      volumeMounts:
        - mountPath: "/data"
          name: task-pv-storage
  nodeName: rhel1
