kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: persistent-volume-claim-nas-clone
  annotations:
     trident.netapp.io/snapshotPolicy: "default"
     trident.netapp.io/snapshotDirectory: "true"
     trident.netapp.io/cloneFromPVC: persistent-volume-claim-nas
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: nas-silver
  