apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nas-silver
provisioner: csi.trident.netapp.io
parameters:
  backendType: "ontap-nas"
  provisioningType: "thin"
  encryption: "false"
allowVolumeExpansion: true
